[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -O3 -ffast-math -Wall -Wextra
monitor_speed = 115200

[env:native]
platform = native
build_flags = -std=gnu++17 -Wall -Wextra
